server:
  port: 5002

logging:
  level:
    org.springframework.cloud.sleuth: DEBUG
    
  file: demo-service.log
management:
  security:
    enabled: false
    
    
empUrl: http://localhost:5003/demo/employee    